base_url = "http://www.ekaterinalarionova.eu/"
title = "Ekaterina Larionova"
description = "Personal site built with Zola and Portio theme"
default_language = "en"
theme = "portio-zola"
compile_sass = true
build_search_index = true

[markdown]
#highlight_code = true
#highlight_theme = "base16-ocean-dark"

[extra]
author = "Ekaterina Larionova"
